import { Lesson, Unit } from "@/lib/types";

type LessonSeed = {
  title: string;
  description: string;
  keyTakeaway: string;
  goodPrompt: string;
  weakPrompt: string;
  quizPrompt: string;
  quizOptions: string[];
  quizAnswer: number;
  quizExplanation: string;
  practicePrompt: string;
  practiceGoal: string;
  builderPieces: string[];
  recommendedPieces: string[];
};

type UnitSeed = {
  id: string;
  title: string;
  subtitle: string;
  color: string;
  modelFocus: Unit["modelFocus"];
  lessons: LessonSeed[];
};

const unitSeeds: UnitSeed[] = [
  {
    id: "unit-1",
    title: "Prompting Fundamentals",
    subtitle: "Build prompts with structure and intent",
    color: "from-blue-500 to-cyan-500",
    modelFocus: "General",
    lessons: [
      {
        title: "What is an image prompt?",
        description: "Understand prompts as creative instructions.",
        keyTakeaway: "A prompt is a compact instruction set that defines what should appear and how it should feel.",
        goodPrompt: "portrait of a ranger, leather cloak, misty forest, soft dawn light",
        weakPrompt: "cool image",
        quizPrompt: "Which option gives the model the clearest creative direction?",
        quizOptions: ["cool image", "make art", "portrait of a ranger in a misty forest at dawn", "something fantasy"],
        quizAnswer: 2,
        quizExplanation: "Specific subject + environment + lighting gives reliable direction.",
        practicePrompt: "Build a clear base prompt for a fantasy character.",
        practiceGoal: "Create a character prompt that names subject, appearance, place, and mood.",
        builderPieces: ["ranger", "misty forest", "dawn lighting", "portrait", "flying car", "random style"],
        recommendedPieces: ["ranger", "misty forest", "dawn lighting", "portrait"],
      },
      {
        title: "How image models interpret prompts",
        description: "Learn token influence and ambiguity.",
        keyTakeaway: "Models weigh frequent visual concepts first; vague words usually produce unstable outputs.",
        goodPrompt: "full body warrior, low angle, storm clouds, dramatic rim light",
        weakPrompt: "epic vibe",
        quizPrompt: "Why do prompts with visual nouns and modifiers usually perform better?",
        quizOptions: ["They are shorter", "They map to recognizable image concepts", "They hide style", "They remove composition"],
        quizAnswer: 1,
        quizExplanation: "Recognizable concepts anchor generation.",
        practicePrompt: "Rewrite a vague prompt into clear visual language.",
        practiceGoal: "Convert broad mood words into observable elements.",
        builderPieces: ["warrior", "low angle", "storm clouds", "dramatic rim light", "nice", "awesome"],
        recommendedPieces: ["warrior", "low angle", "storm clouds", "dramatic rim light"],
      },
      {
        title: "Subjects",
        description: "Define who or what appears in frame.",
        keyTakeaway: "Strong prompts begin with unambiguous subject definitions.",
        goodPrompt: "solo female pilot with silver hair",
        weakPrompt: "person",
        quizPrompt: "What improves subject control most?",
        quizOptions: ["Adding random adjectives", "Naming role and notable traits", "Removing nouns", "Only using style terms"],
        quizAnswer: 1,
        quizExplanation: "Role + traits prevent generic subject output.",
        practicePrompt: "Describe a distinct subject for sci-fi art.",
        practiceGoal: "Define one subject with role and two traits.",
        builderPieces: ["female pilot", "silver hair", "solo", "blue flight suit", "crowd", "blur"],
        recommendedPieces: ["female pilot", "silver hair", "solo", "blue flight suit"],
      },
      {
        title: "Appearance",
        description: "Guide facial and visual identity.",
        keyTakeaway: "Appearance descriptors improve repeatability across attempts.",
        goodPrompt: "sharp jawline, blue eyes, braided silver hair",
        weakPrompt: "looks cool",
        quizPrompt: "Which phrase adds concrete appearance detail?",
        quizOptions: ["looks cool", "high quality", "blue eyes and braided silver hair", "good art"],
        quizAnswer: 2,
        quizExplanation: "Concrete facial and hair detail improves consistency.",
        practicePrompt: "Create a detailed hero appearance block.",
        practiceGoal: "Add face, hair, and color detail.",
        builderPieces: ["blue eyes", "braided silver hair", "defined features", "confident expression", "nice style"],
        recommendedPieces: ["blue eyes", "braided silver hair", "defined features", "confident expression"],
      },
      {
        title: "Clothing and accessories",
        description: "Control outfit-driven storytelling.",
        keyTakeaway: "Outfits carry genre and character role instantly.",
        goodPrompt: "black tactical jacket, red scarf, fingerless gloves",
        weakPrompt: "wearing clothes",
        quizPrompt: "Which accessory phrase is specific and useful?",
        quizOptions: ["stylish", "red scarf and black tactical jacket", "fashion", "dressed up"],
        quizAnswer: 1,
        quizExplanation: "Named garments and colors are directly visual.",
        practicePrompt: "Design a recognizable outfit.",
        practiceGoal: "Use at least three explicit clothing cues.",
        builderPieces: ["black tactical jacket", "red scarf", "utility belt", "fingerless gloves", "good outfit"],
        recommendedPieces: ["black tactical jacket", "red scarf", "utility belt", "fingerless gloves"],
      },
      {
        title: "Actions and poses",
        description: "Add movement and intent.",
        keyTakeaway: "Action verbs and pose hints shape energy.",
        goodPrompt: "warrior raising sword, forward stance, wind-blown cloak",
        weakPrompt: "standing",
        quizPrompt: "Which option creates the strongest motion cue?",
        quizOptions: ["standing", "raising sword with forward stance", "good pose", "centered"],
        quizAnswer: 1,
        quizExplanation: "Action + body orientation communicates intent.",
        practicePrompt: "Turn a static prompt dynamic.",
        practiceGoal: "Add one action and one pose descriptor.",
        builderPieces: ["raising sword", "forward stance", "wind-blown cloak", "motion blur", "still"],
        recommendedPieces: ["raising sword", "forward stance", "wind-blown cloak", "motion blur"],
      },
      {
        title: "Environments",
        description: "Build context and location.",
        keyTakeaway: "Environment details define narrative and mood.",
        goodPrompt: "rainy cyberpunk street, neon signs, wet reflections",
        weakPrompt: "in a place",
        quizPrompt: "Which phrase best establishes environment atmosphere?",
        quizOptions: ["in a place", "rainy cyberpunk street with neon reflections", "scenery", "background"],
        quizAnswer: 1,
        quizExplanation: "Location + weather + lighting creates setting depth.",
        practicePrompt: "Write a cinematic city environment.",
        practiceGoal: "Specify time, weather, and at least one material detail.",
        builderPieces: ["rainy street", "neon signs", "wet pavement", "night", "somewhere"],
        recommendedPieces: ["rainy street", "neon signs", "wet pavement", "night"],
      },
      {
        title: "Combining prompt elements",
        description: "Assemble complete prompts end-to-end.",
        keyTakeaway: "Ordering from subject to style improves clarity.",
        goodPrompt: "silver-haired warrior, black jacket and red scarf, low angle, stormy mountain, dramatic lighting, painterly fantasy style",
        weakPrompt: "fantasy dramatic cool warrior maybe",
        quizPrompt: "What order is most useful for consistent prompting?",
        quizOptions: ["style first only", "subject → details → action → environment → composition → lighting → style", "random words", "negative prompt first"],
        quizAnswer: 1,
        quizExplanation: "Structured ordering reduces ambiguity.",
        practicePrompt: "Create a full structured prompt.",
        practiceGoal: "Include all major layers from subject to style.",
        builderPieces: ["silver-haired warrior", "black jacket", "low angle", "stormy mountain", "dramatic lighting", "painterly style"],
        recommendedPieces: ["silver-haired warrior", "black jacket", "low angle", "stormy mountain", "dramatic lighting", "painterly style"],
      },
    ],
  },
  {
    id: "unit-2",
    title: "Subject Control",
    subtitle: "Build consistent characters and objects",
    color: "from-fuchsia-500 to-pink-500",
    modelFocus: "General",
    lessons: [
      ["Describing people", "human portraits"],
      ["Describing creatures", "mythic beings"],
      ["Describing objects", "prop-focused scenes"],
      ["Facial features", "face detail control"],
      ["Hair", "hair texture and color"],
      ["Clothing", "wardrobe consistency"],
      ["Accessories", "identity markers"],
      ["Character consistency", "reusable descriptor blocks"],
    ].map(([title, angle]) => ({
      title,
      description: `Improve ${angle} prompting with measurable details.`,
      keyTakeaway: "Consistency comes from reusing a stable subject descriptor stack.",
      goodPrompt: "1 character, silver hair, blue eyes, black jacket, red scarf, solo",
      weakPrompt: "anime person",
      quizPrompt: `Which prompt best supports ${title.toLowerCase()} control?`,
      quizOptions: ["anime person", "1 character, silver hair, blue eyes, black jacket, red scarf", "nice art", "masterpiece"],
      quizAnswer: 1,
      quizExplanation: "Specific repeated attributes keep identity stable.",
      practicePrompt: "Create a consistent character prompt with fixed attributes.",
      practiceGoal: "Build a reusable descriptor block for the same character.",
      builderPieces: ["silver hair", "blue eyes", "black jacket", "red scarf", "solo", "random"],
      recommendedPieces: ["silver hair", "blue eyes", "black jacket", "red scarf", "solo"],
    })),
  },
  {
    id: "unit-3",
    title: "Composition",
    subtitle: "Control framing and shot type",
    color: "from-cyan-500 to-blue-600",
    modelFocus: "General",
    lessons: ["close-up", "portrait", "upper body", "medium shot", "cowboy shot", "full body", "wide shot"].map((shot) => ({
      title: `${shot} composition`,
      description: `Learn when to use ${shot} framing.`,
      keyTakeaway: "Composition terms define how much of subject and scene is visible.",
      goodPrompt: `${shot}, solo character, clear silhouette`,
      weakPrompt: "show character",
      quizPrompt: "Which option is most likely to show the entire character?",
      quizOptions: ["close-up", "portrait", "full body", "extreme close-up"],
      quizAnswer: 2,
      quizExplanation: "Full body framing includes the complete character.",
      practicePrompt: `Write a ${shot} prompt for a hero scene.`,
      practiceGoal: "Match shot type to storytelling intent.",
      builderPieces: ["close-up", "portrait", "medium shot", "cowboy shot", "full body", "wide shot"],
      recommendedPieces: [shot],
    })),
  },
  {
    id: "unit-4",
    title: "Camera Angles",
    subtitle: "Shape emotion with perspective",
    color: "from-violet-500 to-indigo-600",
    modelFocus: "General",
    lessons: [
      ["Eye level", "neutral"],
      ["Low angle", "powerful"],
      ["High angle", "vulnerable"],
      ["From above", "overview"],
      ["Profile and side view", "silhouette"],
      ["Three-quarter view", "depth"],
      ["Dutch angle", "unease"],
    ].map(([title, mood]) => ({
      title,
      description: `Use ${title.toLowerCase()} for ${mood} tone.`,
      keyTakeaway: "Camera perspective changes perceived status and drama.",
      goodPrompt: `${title.toLowerCase()}, warrior on castle stairs, dramatic light`,
      weakPrompt: "cool camera",
      quizPrompt: "Which angle usually makes a character feel powerful?",
      quizOptions: ["high angle", "low angle", "top down", "flat profile"],
      quizAnswer: 1,
      quizExplanation: "Low angle elevates subject dominance.",
      practicePrompt: `Create a scene using ${title.toLowerCase()} perspective.`,
      practiceGoal: "Tie camera angle to emotional goal.",
      builderPieces: ["eye level", "low angle", "high angle", "from above", "three-quarter view", "dutch angle"],
      recommendedPieces: [title.toLowerCase()],
    })),
  },
  {
    id: "unit-5",
    title: "Lighting",
    subtitle: "Direct mood with light behavior",
    color: "from-amber-400 to-orange-600",
    modelFocus: "General",
    lessons: [
      "soft lighting",
      "hard lighting",
      "dramatic lighting",
      "rim lighting",
      "backlighting",
      "volumetric lighting",
      "neon lighting",
      "golden hour",
    ].map((lighting) => ({
      title: lighting,
      description: `Control scene emotion using ${lighting}.`,
      keyTakeaway: "Lighting terms are high-leverage style and readability controls.",
      goodPrompt: `futuristic city scene, rain, reflections, ${lighting}`,
      weakPrompt: "nice light",
      quizPrompt: "What lighting concept is best for moody cyberpunk atmosphere?",
      quizOptions: ["flat noon light", "neon lighting", "white background", "none"],
      quizAnswer: 1,
      quizExplanation: "Neon lighting with rain reflections creates atmospheric futuristic mood.",
      practicePrompt: `Design a prompt emphasizing ${lighting}.`,
      practiceGoal: "Use one primary and one secondary light cue.",
      builderPieces: ["dramatic lighting", "rim lighting", "backlighting", "neon lighting", "rain reflections", "flat light"],
      recommendedPieces: [lighting],
    })),
  },
  {
    id: "unit-6",
    title: "Environments & Atmosphere",
    subtitle: "Build depth and narrative context",
    color: "from-emerald-500 to-teal-600",
    modelFocus: "General",
    lessons: [
      "Backgrounds and foregrounds",
      "Depth cues",
      "Weather systems",
      "Time of day",
      "Atmospheric effects",
      "Environmental storytelling",
      "Cinematic transformation",
    ].map((title) => ({
      title,
      description: "Turn simple prompts into immersive scenes.",
      keyTakeaway: "Atmosphere is created by layering weather, depth, and temporal cues.",
      goodPrompt: "woman standing in futuristic city at night, rain, neon signs, wet pavement reflections, cinematic lighting",
      weakPrompt: "woman in city",
      quizPrompt: "Which addition most improves cinematic atmosphere?",
      quizOptions: ["city", "rain + neon reflections + night", "person", "style"],
      quizAnswer: 1,
      quizExplanation: "Layered environmental cues create visual narrative.",
      practicePrompt: "Upgrade a minimal city prompt to cinematic quality.",
      practiceGoal: "Add weather, time, lighting, and material detail.",
      builderPieces: ["rain", "fog", "neon signs", "wet pavement", "sunset", "storm clouds"],
      recommendedPieces: ["rain", "neon signs", "wet pavement"],
    })),
  },
  {
    id: "unit-7",
    title: "Illustrious Prompting",
    subtitle: "Master tag-first prompting",
    color: "from-purple-500 to-fuchsia-600",
    modelFocus: "Illustrious",
    lessons: [
      "Tag-oriented prompting",
      "Descriptive prompting",
      "Hybrid prompting",
      "Composition tags",
      "Character tags",
      "Environment tags",
      "Prompt organization",
    ].map((title) => ({
      title,
      description: "Practice Illustrious-compatible prompt structuring.",
      keyTakeaway: "Illustrious workflows often respond well to ordered, concise visual tags.",
      goodPrompt: "1girl, solo, long white hair, blue eyes, black jacket, cityscape, night, rain, looking_at_viewer, neon_lights",
      weakPrompt: "draw anime",
      quizPrompt: "Which format best matches tag-oriented prompting?",
      quizOptions: ["single vague sentence", "ordered concept tags", "negative prompt only", "random punctuation"],
      quizAnswer: 1,
      quizExplanation: "Ordered tags improve reproducibility for tag-centric models.",
      practicePrompt: "Build a hybrid Illustrious prompt (tags + sentence).",
      practiceGoal: "Use character tags, composition tags, and environment tags.",
      builderPieces: ["1girl", "solo", "long white hair", "blue eyes", "black jacket", "cityscape", "night", "rain", "neon_lights"],
      recommendedPieces: ["1girl", "solo", "long white hair", "blue eyes", "cityscape", "night", "rain"],
    })),
  },
  {
    id: "unit-8",
    title: "SDXL Prompting",
    subtitle: "Natural language + structure",
    color: "from-sky-500 to-indigo-500",
    modelFocus: "SDXL",
    lessons: [
      "Natural language prompting",
      "Structured descriptions",
      "Hybrid prompts",
      "Scene descriptions",
      "Composition control",
      "Lighting control",
      "Specificity strategy",
    ].map((title) => ({
      title,
      description: "Tune SDXL prompts for clarity and control.",
      keyTakeaway: "SDXL often benefits from coherent scene-language with specific visual constraints.",
      goodPrompt: "A cinematic portrait of a woman with silver hair standing on a rainy rooftop overlooking a futuristic city at night. Neon signs illuminate her face with blue and magenta light.",
      weakPrompt: "woman, city",
      quizPrompt: "When is natural-language prompting especially useful?",
      quizOptions: ["Never", "When describing cohesive scene context and mood", "Only for negatives", "Only for tags"],
      quizAnswer: 1,
      quizExplanation: "Scene-level coherence is a strength of well-written natural descriptions.",
      practicePrompt: "Write both natural and tag-like versions of one SDXL concept.",
      practiceGoal: "Compare concise vs narrative SDXL prompt style.",
      builderPieces: ["cinematic portrait", "rainy rooftop", "futuristic city", "night", "blue and magenta neon light", "silver hair"],
      recommendedPieces: ["cinematic portrait", "rainy rooftop", "futuristic city", "blue and magenta neon light"],
    })),
  },
  {
    id: "unit-9",
    title: "Anima Prompting",
    subtitle: "Experiment-driven model adaptation",
    color: "from-rose-500 to-pink-600",
    modelFocus: "Anima",
    lessons: [
      "Model-specific caution",
      "Testing prompt phrasing",
      "Tag style experiments",
      "Natural language experiments",
      "Comparing outputs",
      "Finding model preferences",
    ].map((title) => ({
      title,
      description: "Use controlled experiments to discover Anima behaviors.",
      keyTakeaway: "Do not assume exact model behavior; validate with repeatable A/B tests.",
      goodPrompt: "silver-haired woman, cyberpunk city, night",
      weakPrompt: "best quality",
      quizPrompt: "What is the safest way to learn model preferences?",
      quizOptions: ["Assume online claims are always true", "Run controlled comparisons with one variable changed", "Use random prompts", "Ignore version differences"],
      quizAnswer: 1,
      quizExplanation: "Controlled experimentation is reliable and transferable across models.",
      practicePrompt: "Create Prompt A and Prompt B differing by one phrasing choice.",
      practiceGoal: "Document outcome differences and keep all other variables fixed.",
      builderPieces: ["Prompt A", "Prompt B", "same seed/settings", "one changed phrase", "result notes"],
      recommendedPieces: ["Prompt A", "Prompt B", "same seed/settings", "one changed phrase", "result notes"],
    })),
  },
  {
    id: "unit-10",
    title: "Advanced Prompting",
    subtitle: "Debug and iterate like a pro",
    color: "from-indigo-500 to-purple-700",
    modelFocus: "General",
    lessons: [
      "Prompt emphasis",
      "Weighting concepts",
      "Concept ordering",
      "Avoiding conflicts",
      "Negative prompts",
      "Change One Thing",
      "Prompt debugging workflow",
      "Experimental methodology",
    ].map((title) => ({
      title,
      description: "Develop a repeatable high-signal iteration process.",
      keyTakeaway: "Small controlled edits produce interpretable improvements.",
      goodPrompt: "knight standing in front of a castle, low angle, dramatic lighting",
      weakPrompt: "knight awesome masterpiece ultra",
      quizPrompt: "Why is the 'Change One Thing' method effective?",
      quizOptions: ["It speeds randomization", "It isolates causal impact of each concept", "It removes creativity", "It avoids testing"],
      quizAnswer: 1,
      quizExplanation: "Holding variables constant lets you learn what changed the output.",
      practicePrompt: "Create V1, V2, V3 prompt iterations for one scene.",
      practiceGoal: "Add one controlled concept per version and observe effect.",
      builderPieces: ["V1 base scene", "V2 + low angle", "V3 + dramatic lighting", "same subject", "same environment"],
      recommendedPieces: ["V1 base scene", "V2 + low angle", "V3 + dramatic lighting", "same subject", "same environment"],
    })),
  },
];

const buildSections = (seed: LessonSeed): Lesson["sections"] => [
  {
    id: "intro",
    title: "Introduction",
    content: `${seed.description} In this lesson you will practice a concrete skill and apply it immediately.`,
  },
  {
    id: "explanation",
    title: "Explanation",
    content: seed.keyTakeaway,
  },
  {
    id: "examples",
    title: "Examples",
    content: `Stronger: "${seed.goodPrompt}"\n\nWeaker: "${seed.weakPrompt}"\n\nNotice how the stronger version uses explicit visual language that can be interpreted consistently.`,
  },
  {
    id: "interactive",
    title: "Interactive Activity",
    content: `${seed.practiceGoal} Use the Prompt Builder below to choose concepts that match the goal.`,
  },
  {
    id: "practice",
    title: "Practice",
    content: seed.practicePrompt,
  },
];

export const COURSE_UNITS: Unit[] = unitSeeds.map((unitSeed) => ({
  id: unitSeed.id,
  title: unitSeed.title,
  subtitle: unitSeed.subtitle,
  color: unitSeed.color,
  modelFocus: unitSeed.modelFocus,
  lessons: unitSeed.lessons.map((seed, lessonIndex) => ({
    id: `${unitSeed.id}-lesson-${lessonIndex + 1}`,
    unitId: unitSeed.id,
    title: seed.title,
    description: seed.description,
    xpReward: 20,
    sections: buildSections(seed),
    quiz: {
      id: `${unitSeed.id}-lesson-${lessonIndex + 1}-quiz`,
      prompt: seed.quizPrompt,
      options: seed.quizOptions,
      answerIndex: seed.quizAnswer,
      explanation: seed.quizExplanation,
    },
    practicePrompt: seed.practicePrompt,
    promptBuilder: {
      goal: seed.practiceGoal,
      pieces: seed.builderPieces,
      recommendedPieces: seed.recommendedPieces,
      explanation: "Try selecting the pieces that best satisfy the goal. You can retry and refine.",
    },
  })),
}));

export const TOTAL_LESSON_COUNT = COURSE_UNITS.reduce((sum, unit) => sum + unit.lessons.length, 0);

export const ALL_LESSONS = COURSE_UNITS.flatMap((unit) => unit.lessons);
